### ISSUE TITLE
XDG_SESSION_TYPE Error

### ISSUE THREAD

**Issue by WeiXikai** [gonzaarcr/Fildem#10]
Hello, here is something error on my computer, and I need some help.

I have already set up those dependence, also the fildemGMenu@gonza.com folder to extensions folder.

Then I copy all these files to ~/.fildem and run `sudo sh run.sh`, and then I get the following things in my terminal:

```
run.sh: 3: [: =: unexpected operator
Traceback (most recent call last):
  File "./command.py", line 7, in <module>
    from handlers.default import HudMenu
  File "/home/weixikai/.fildem/handlers/default.py", line 16, in <module>
    from utils.menu import WindowActions
  File "/home/weixikai/.fildem/utils/menu.py", line 10, in <module>
    from utils.window import WindowManager
  File "/home/weixikai/.fildem/utils/window.py", line 18, in <module>
    backend = os.environ['XDG_SESSION_TYPE']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_SESSION_TYPE'
```

Then the program exit.

Also I opened this extension in tweaks, but nothing happened.

That's all. Thank you.

**Comment by gonzaarcr** [comment]
Hello! Don’t use `sudo`

**Comment by WeiXikai** [comment]
> Hello! Don’t use `sudo`

Ok, that's it! It works! Nice and useful extension! Thank you.
