### ISSUE TITLE
Not working with Arch Linux

### ISSUE THREAD

**Issue by darthoctopus** [gonzaarcr/Fildem#104]
### Information

- **Operating System**: Arch Linux
- **Gnome Shell Version**: 40.4
- **Xorg/Wayland?**: Xorg
- **Apps tested**: N/A
- **Fildem version**: current git master

### What is the current behavior?

When `fildem` is run from the command line, the following exception is raised:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/fildem/keybinder.py", line 30, in main
    run_keybinder(default_hud_menu)
  File "/usr/lib/python3.9/site-packages/fildem/keybinder.py", line 19, in run_keybinder
    dbus_menu = DbusMenu()
  File "/usr/lib/python3.9/site-packages/fildem/utils/menu.py", line 28, in __init__
    self._init_window()
  File "/usr/lib/python3.9/site-packages/fildem/utils/menu.py", line 35, in _init_window
    self.appmenu = DbusAppMenu(self.session, self.window)
  File "/usr/lib/python3.9/site-packages/fildem/menu_model/menu_model.py", line 128, in __init__
    self.interface = self.get_interface()
  File "/usr/lib/python3.9/site-packages/fildem/menu_model/menu_model.py", line 157, in get_interface
    object     = self.session.get_object(name, path)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 241, in __init__
    _dbus_bindings.validate_bus_name(bus_name)
ValueError: Invalid bus name: may not be empty
```

### Steps to reproduce the problem

Run `fildem` from the command line

### What is the expected behavior?

No error is thrown

**Comment by gsingh704** [comment]
Same for me
