### ISSUE TITLE
Crash after click on PHPStorm navbar

### ISSUE THREAD

**Issue by 7system7** [gonzaarcr/Fildem#108]
### Information

- **Operating System**: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```
- **Gnome Shell Version**: 3.38.5
- **Xorg/Wayland?**: Xorg
- **Apps tested**:  Java, PHPStorm
- **Fildem version**: 0.6.7 (latest)
- **nVidia driver version**:  NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4
- **PHPStorm version**:

```
PhpStorm 2021.2.2
Build #PS-212.5284.49, built on September 16, 2021
Licensed to ...
Subscription is active until September 25, 2021.
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-36-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry: debugger.watches.in.variables=false, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.ideolog (203.0.27.0), cn.haojiyou.CodeGlance3 (2.1.1-2021.1.3), com.karateca.jstoolbox (1.10), com.intellij.jira (3.6.0), com.darkyen.darkyenustimetracker (1.5.1), ru.mobiledev.plugins.uigd (1.2), mobi.hsz.idea.gitignore (4.2.0), com.atlassian.bitbucket.references (2021.2.188), zielu.gittoolbox (212.7.11), com.jinsihou.react.snippets (1.1.0), com.intellij.javafx (1.0.3), de.espend.idea.php.phpunit (6.2), de.espend.idea.php.toolbox (6.0.0), de.espend.idea.php.annotation (8.0.0), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), fr.adrienbrault.idea.symfony2plugin (0.23.212), ru.adelf.idea.dotenv (2021.3.0.212), de.timo_reymann.intellij-mjml-support (1.17.0), lermitage.intellij.extra.icons (1.62.0.203), com.intellij.react.css.modules (1.0.1), net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0), lv.midiana.misc.idea-plugins.deep-js-completion (2021.04.21.002)
Current Desktop: ubuntu:GNOME
```

### What is the current behavior?

Fildem is working w/ anything except the Jetbrains apps. I.e.: ffter I click on any menu item in PHPStorm, then there are 2 options of output:

1. The menu is working but nothing happens after click on them.
1. The menu is working but after I click on an item, the fildem service stops working completely. And it won't work w/ any other program too.

#### Log
```console
** (-c:97458): WARNING **: 12:00:11.957: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.application” on object at path /org/ayatana/bamf/application/0x55a3295f9b90

(-c:97458): Gtk-CRITICAL **: 12:01:16.283: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:97458): Gtk-CRITICAL **: 12:01:16.290: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:97458): Gtk-WARNING **: 12:01:16.303: no trigger event for menu popup

(-c:97458): Gtk-CRITICAL **: 12:02:03.896: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:97458): Gtk-CRITICAL **: 12:02:03.899: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:97458): Gtk-WARNING **: 12:02:03.909: no trigger event for menu popup
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fildem/handlers/global_menu.py", line 335, in do_activate
    self.add_menus()
  File "/usr/lib/python3/dist-packages/fildem/handlers/global_menu.py", line 344, in add_menus
    self.window.set_menu(self.dbus_menu.items)
  File "/usr/lib/python3/dist-packages/fildem/handlers/global_menu.py", line 192, in set_menu
    current_prefix = menus[0].path[0]
IndexError: list index out of range
```

### Steps to reproduce the problem

1. Install latest PHPstorm
2. Install the [mentioned plugin](https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins)
3. Start fildem python service
4. Enable fildem GNOME ext.
5. Start PHPStorm
6. Click on any menu item

### What is the expected behavior?

**Working PHPStorm menu items.**

**Comment by tborowy** [comment]
I have the same problem with WebStorm.

**Comment by tomaswarynyca** [comment]
@gonzaarcr do you have any idea how to solve this?

**Comment by aliyazdi75** [comment]
@7system7 
Does this package maintain anymore? Is there any alternative? I couldn't find one :(
