### ISSUE TITLE
No package metadata was found for fildem

### ISSUE THREAD

**Issue by hansjohn** [gonzaarcr/Fildem#117]
### Information

- **Operating System**:  Arch
- **Gnome Shell Version**: 41.2
- **Xorg/Wayland?**: xorg
- **Apps tested**:  
- **Fildem version**: 0.6.7

### What is the current behavior?
can't start

Traceback (most recent call last):
  File "/usr/bin/fildem", line 33, in <module>
    sys.exit(load_entry_point('fildem==0.6.7', 'console_scripts', 'fildem')())
  File "/usr/bin/fildem", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for fildem

### Steps to reproduce the problem
run fildem

**Comment by hewenjin** [comment]
some issue and environment here.
I'm trying to solve it by myself, and I find [this](https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/) from reddit, after rebuild Fildem from source, I got this:
`
Traceback (most recent call last):
  File "/home/hewenjin/project/Fildem/src/Fildem/setup.py", line 8, in <module>
    setuptools.setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 232, in run
    self.run_tests()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 250, in run_tests
    test = unittest.main(
  File "/usr/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.10/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.10/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.10/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.10/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 50, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.10/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 50, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/hewenjin/project/Fildem/src/Fildem/fildem/utils/menu.py", line 6, in <module>
    from fildem.utils.window import WindowManager
  File "/home/hewenjin/project/Fildem/src/Fildem/fildem/utils/window.py", line 18, in <module>
    wayland = is_wayland()
  File "/home/hewenjin/project/Fildem/src/Fildem/fildem/utils/wayland.py", line 8, in is_wayland
    return 'wayland' in (disp or type)
TypeError: argument of type 'NoneType' is not iterable
==> ERROR: A failure occurred in check().
    Aborting...
`
now I'm pretty sure Fildem need to update for python 3.10

**Comment by mhmtkrktr** [comment]
It doesn't work for me either after gnome 41 version.
was working before

Operating System: Arch
Gnome Shell Version: 41.2
Xorg/Wayland?: xorg / wayland
Fildem version: 0.6.7

`fildem
Traceback (most recent call last):
  File "/usr/bin/fildem", line 33, in <module>
    sys.exit(load_entry_point('fildem==0.6.7', 'console_scripts', 'fildem')())
  File "/usr/bin/fildem", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for fildem`

`python --version
Python 3.10.1`

**Comment by yilozt** [comment]
Same problem. After add some soft link by `ln -s`,  it works with python 3.10 in my Arch Linux now:

```sh
sudo ln -s /usr/lib/python3.9/site-packages/fildem /usr/lib/python3.10/site-packages 
sudo ln -s /usr/lib/python3.9/site-packages/fildem-0.6.7-py3.9.egg-info/ /usr/lib/python3.10/site-packages
```

- Operating System: Arch Linux
- Gnome Shell Version: 41.3
- Xorg/Wayland: xorg

**Comment by mhmtkrktr** [comment]
It worked for me too. Thanks yilozt

**Comment by hansjohn** [comment]
it worked.thank you!

**Comment by hrqmonteiro** [comment]
> Same problem. After add some soft link by `ln -s`, it works with python 3.10 in my Arch Linux now:
> 
> ```shell
> sudo ln -s /usr/lib/python3.9/site-packages/fildem /usr/lib/python3.10/site-packages 
> sudo ln -s /usr/lib/python3.9/site-packages/fildem-0.6.7-py3.9.egg-info/ /usr/lib/python3.10/site-packages
> ```
> 
>     * Operating System: Arch Linux
> 
>     * Gnome Shell Version: 41.3
> 
>     * Xorg/Wayland: xorg

How to fix these?

```
[hrq@fedora ~]$ fildem
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/window.py", line 155, in _window_switched
    cls._call_all_listeners(win)
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/window.py", line 160, in _call_all_listeners
    callback(window)
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 42, in on_window_switched
    self._init_window()
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 37, in _init_window
    self._update()
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 125, in _update
    self._update_menus()
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 117, in _update_menus
    self.appmenu.get_results()
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/menu_model/menu_model.py", line 167, in get_results
    self.results = self.interface.GetLayout(0, -1, dbus.Array(signature="s"))
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/com/canonical/menu/E00003”
```
