### ISSUE TITLE
not an issue, i just want to report that it perfectly works on fedora 35 with gnome 41.2 (wayland)

### ISSUE THREAD

**Issue by stem2580** [gonzaarcr/Fildem#121]
![Screenshot from 2021-12-25 00-02-02](https://user-images.githubusercontent.com/37732484/147373879-91a0c88c-8bc2-4c4e-9e6a-1e1b0d948645.png)

**Comment by WhiteCzar** [comment]
How did you get it to work? I have Fedora 35 and I can't enable the extension from Gnome Tweaks.

**Comment by stem2580** [comment]
> How did you get it to work? I have Fedora 35 and I can't enable the extension from Gnome Tweaks.

you need to enable it from the extensions app, gnome tweaks doesn't support managing extensions anymore

**Comment by WhiteCzar** [comment]
Yes, I meant the extensions app. I can't enable it from there.

**Comment by WhiteCzar** [comment]
![image](https://user-images.githubusercontent.com/85533924/147378990-5f0c0ccc-b617-4f13-b908-c1ae955d2b4c.png)

**Comment by stem2580** [comment]
weird, maybe tru adding version 41 to:
![image](https://user-images.githubusercontent.com/37732484/147379023-3461e11d-6fe3-4a07-9a99-923823aa4fbf.png)

**Comment by stem2580** [comment]
and reboot!

**Comment by WhiteCzar** [comment]
![Screenshot from 2021-12-25 14-42-28](https://user-images.githubusercontent.com/85533924/147379140-bb1dfb5c-ecea-4235-81d8-27b369dfb38a.png)

Yeah, it started now, but it's still not working properly.

**Comment by WhiteCzar** [comment]
Terminal gives some errors:

(-c:3059): Gtk-WARNING **: 14:40:07.668: no trigger event for menu popup

(-c:3059): Gtk-WARNING **: 14:41:18.538: no trigger event for menu popup

(-c:3059): Gtk-WARNING **: 14:41:22.627: no trigger event for menu popup

(-c:3059): Gtk-WARNING **: 14:45:02.147: no trigger event for menu popup

**Comment by WhiteCzar** [comment]
Can you use LibreOffice properly with Global Menu?

**Comment by stem2580** [comment]
install these:
`sudo dnf install bamf bamf-daemon keybinder3 unity-gtk2-module unity-gtk3-module appmenu-qt5 appmenu-qt5-profile.d python3-pip git`

open gtkrc-2.0 file: `gedit ~/.gtkrc-2.0` 
add the following line: `gtk-modules="appmenu-gtk-module"`
open settings.ini file: `gedit ~/.config/gtk-3.0/settings.ini`
add the following 2 lines:
```
[Settings]
gtk-modules="appmenu-gtk-module"
```

logout / login and it should work

**Comment by WhiteCzar** [comment]
I did all that. I followed this article:

https://www.linuxuprising.com/2021/02/how-to-install-fildem-global-menu-and.html

Unfortunately, the above screenshot is the result. But can you open LibreOffice and have the menu work with it?

**Comment by WhiteCzar** [comment]
Also, did you install the latest version? 0.6.7?

**Comment by stem2580** [comment]
> Also, did you install the latest version? 0.6.7?

yes, i also followed that article an it works, even libreoffice
![image](https://user-images.githubusercontent.com/37732484/147379403-320c6df9-464a-4f95-812c-437b5cd04551.png)

**Comment by WhiteCzar** [comment]
Weird...

**Comment by WhiteCzar** [comment]
Oh! I figured what the problem was. I had another extensions called Scroll Panel installed. It is incompatible with the Global Menu apparently. Once I turned Scroll Panel, the Global Menu now works like a charm! Thank you!

**Comment by Ahmed-gubara** [comment]
Following your link worked on Manjaro with Gnome 41.2 (X11). Thank you

**Comment by igor-kobzev** [comment]
@gonzaarcr Can you update the release to enable out-of-the-box support for Gnome 41?

**Comment by hrqmonteiro** [comment]
> ![Screenshot from 2021-12-25 00-02-02](https://user-images.githubusercontent.com/37732484/147373879-91a0c88c-8bc2-4c4e-9e6a-1e1b0d948645.png)

My dude, following your EXACT steps just literally doesn't work. When i open Fildem, i get this:

```
[hrq@fedora ~]$ killall fildem
[hrq@fedora ~]$ killall fildem
fildem: no process found
[hrq@fedora ~]$ killall fildem
fildem: no process found
[hrq@fedora ~]$ fildem

** (-c:3422): WARNING **: 14:41:48.458: Binding '<Alt>space' failed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/window.py", line 150, in _window_switched_bamf
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/window.py", line 160, in _call_all_listeners
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 42, in on_window_switched
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 37, in _init_window
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 125, in _update
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 117, in _update_menus
  File "/usr/local/lib/python3.10/site-packages/fildem-0.6.7-py3.10.egg/fildem/menu_model/menu_model.py", line 167, in get_results
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/com/canonical/menu/2E00003”
```

Are you sure you followed the steps you just said? And nothing more?
