### ISSUE TITLE
Visual Studio Code: Menu items don't execute the command

### ISSUE THREAD

**Issue by nayaabkhan** [gonzaarcr/Fildem#13]
## Description

The menu shows correctly for VS Code but clicking an action doesn't execute it. I see an error in the output of `run.sh`.

## Error

```
(-c:5518): Gtk-WARNING **: 19:37:30.331: no trigger event for menu popup
Traceback (most recent call last):
  File "/home/nayaabkhan/Downloads/Fildem-master/handlers/global_menu.py", line 356, in <lambda>
    callback = lambda a, b: self.dbus_menu.activate(path)
  File "/home/nayaabkhan/Downloads/Fildem-master/utils/menu.py", line 375, in activate
    self.appmenu.activate(selection)
  File "/home/nayaabkhan/Downloads/Fildem-master/utils/menu.py", line 198, in activate
    self.interface.Event(action, 'clicked', 0, 0)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.gtk.GDBus.UnmappedGError.Quark._LIBDBUSMENU_2dGLIB.Code0: The ID supplied 277 does not refer to a menu item we have

```

**Comment by gonzaarcr** [comment]
Fixed on 727581b
