### ISSUE TITLE
ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by soype** [gonzaarcr/Fildem#163]
### Information

I've followed the steps as described in the guide but when I run "fildem" I get an error

- **Operating System**:  Pop!_OS 22.04 LTS x86_64 
- **Gnome Shell Version**: GNOME 42.3.1 
- **Xorg/Wayland?**:  x11
- **Apps tested**:  all
- **Fildem version**: 0.6.7

### What is the current behavior?

I get the following error and Fildem doesn't run
(fildem:21710): Gtk-WARNING **: 21:15:53.207: Theme parsing error: gtk.css:5503:16: not a number
Traceback (most recent call last):
  File "/usr/bin/fildem", line 11, in <module>
    load_entry_point('fildem==0.6.7', 'console_scripts', 'fildem')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.10/dist-packages/fildem-0.6.7-py3.10.egg/fildem/run.py", line 6, in <module>
  File "/usr/local/lib/python3.10/dist-packages/fildem-0.6.7-py3.10.egg/fildem/command.py", line 8, in <module>
  File "/usr/local/lib/python3.10/dist-packages/fildem-0.6.7-py3.10.egg/fildem/handlers/rofi.py", line 10, in <module>
  File "/usr/local/lib/python3.10/dist-packages/fildem-0.6.7-py3.10.egg/fildem/utils/menu.py", line 12, in <module>
  File "/usr/local/lib/python3.10/dist-packages/fildem-0.6.7-py3.10.egg/fildem/menu_model/menu_model.py", line 8, in <module>
  File "/usr/local/lib/python3.10/dist-packages/fildem-0.6.7-py3.10.egg/fildem/treelib/__init__.py", line 38, in <module>
  File "/usr/local/lib/python3.10/dist-packages/fildem-0.6.7-py3.10.egg/fildem/treelib/tree.py", line 41, in <module>
ModuleNotFoundError: No module named 'future'

### Steps to reproduce the problem

pedroh@pop-os:~/Descargas$ fildem

**Comment by grimaldi-dev** [comment]
You can solve this by installing future with 
`pip install -U future`
If you don't have pip installed you can use this command to install it
`sudo apt install python3`
