### ISSUE TITLE
@GrzegorzManiak

### ISSUE THREAD

**Issue by KaKi87** [gonzaarcr/Fildem#178]
Hello @GrzegorzManiak,

Do you intend to keep maintaining your fork of this project ?

If yes, could you please enable issues, make a release and write installation instructions ?

Thanks

**Comment by GrzegorzManiak** [comment]
Hey, sorry for the delayed response, Id love to continue working on this, but I got a role as a Software Engineer at Mastercard so I'm a bit time constrained.

I can open everything up and restart work on this as I see that there's enough interest, it'll just take a few weeks to get back upto speed.

Kindest regards,
Grzegroz

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: KaKi87 ***@***.***>
Sent: Thursday, February 22, 2024 11:14:46 PM
To: gonzaarcr/Fildem ***@***.***>
Cc: X00189661 Grzegorz Maniak ***@***.***>; Mention ***@***.***>
Subject: [gonzaarcr/Fildem] @GrzegorzManiak (Issue #178)


Hello @GrzegorzManiak<https://github.com/GrzegorzManiak>,

Do you intend to keep maintaining your fork of this project ?

If yes, could you please enable issues, make a release and write installation instructions ?

Thanks

**Comment by KaKi87** [comment]
No problem and congrats !

Count me as interested, and count them as interested as well :

| ![](https://github.com/gonzaarcr/Fildem/assets/21284089/1cd496a9-6be9-4548-8a94-781628e1f2cf) | ![](https://github.com/gonzaarcr/Fildem/assets/21284089/49e43ccb-31fa-4674-9b58-08ac0eeedaad)
| - | -
| ![](https://github.com/gonzaarcr/Fildem/assets/21284089/1da2a381-a84d-48a4-9873-68168fcf9a2d) | ![](https://github.com/gonzaarcr/Fildem/assets/21284089/a0d68780-3097-4690-9e79-590ecbfa887e)
| ![](https://github.com/gonzaarcr/Fildem/assets/21284089/db50b7d0-3b33-42cf-8c63-07f04ba654de) | ![](https://github.com/gonzaarcr/Fildem/assets/21284089/eb8b4ac1-f352-43f4-b83f-e0e190d70b84)
| ![](https://github.com/gonzaarcr/Fildem/assets/21284089/f32f35c8-0361-4ef4-99bc-9e68d89e84be) | ![](https://github.com/gonzaarcr/Fildem/assets/21284089/44a9c6c8-2a5b-4033-9240-ca5194196463)
| ![](https://github.com/gonzaarcr/Fildem/assets/21284089/eca0c523-e737-414e-a96f-7400ed49a640) | ![](https://github.com/gonzaarcr/Fildem/assets/21284089/23000409-e508-45ec-a561-b4d292796441)

There's always someone asking every now and then, I hope it's enough motivation and if it is, I'm looking forward to updates :)

**Comment by chaudharyjatin115** [comment]
Hey i would like to co- maintain this  extension   with you  after i get into a college in august kindly let me know  if you are willing to have a co maintainer

**Comment by GrzegorzManiak** [comment]
Hey, I'm welcome to all contributions! I'd probably move away from just forking this repo as not a single LOC made it to my current version.

At that, I'm currently struggling to get apps to 'register' their menus with my DBus service, as I couldnt find a binary that would run the 'com.canonical.menu' service, so I tried re create it, which worked partly, as in Apps would detect that there is a global menu present, and they'd hide their own menues, but they would never register their menues with my service.

As this was more of a 'learning experience' as I wanted to learn more about GTK and DBus, I did not really have a clue on what I was doing, BUT if you know what you are doing, please contribute! I still want a global menu for Gnome!

https://github.com/GrzegorzManiak/FildemRevamped/blob/gnome45/extension/src/dbus/dbusmenu.ts
https://github.com/GrzegorzManiak/FildemRevamped/blob/gnome45/extension/src/dbus/registrar.ts

**Comment by chaudharyjatin115** [comment]
> Hey, I'm welcome to all contributions! I'd probably move away from just forking this repo as not a single LOC made it to my current version.
> 
> At that, I'm currently struggling to get apps to 'register' their menus with my DBus service, as I couldnt find a binary that would run the 'com.canonical.menu' service, so I tried re create it, which worked partly, as in Apps would detect that there is a global menu present, and they'd hide their own menues, but they would never register their menues with my service.
> 
> As this was more of a 'learning experience' as I wanted to learn more about GTK and DBus, I did not really have a clue on what I was doing, BUT if you know what you are doing, please contribute! I still want a global menu for Gnome!
> 
> https://github.com/GrzegorzManiak/FildemRevamped/blob/gnome45/extension/src/dbus/dbusmenu.ts https://github.com/GrzegorzManiak/FildemRevamped/blob/gnome45/extension/src/dbus/registrar.ts

hey i  will be able to contribute to it after june maybe due do college and things  also we actually have a working version  which supports even gnome 46

**Comment by GrzegorzManiak** [comment]
Do you have a working version!?! I'd love to see it! 

For now I created a minimal project just to access the dbus:
https://github.com/GrzegorzManiak/GnomeGlobalMenu

This also allows for development without reinstalling the extension over and over.

**Comment by chaudharyjatin115** [comment]
hey you can check in pull request i have been using it from a while it works fine altho i did some modifications to get it working on my arch setup

**Comment by 7system7** [comment]
The project is not working anymore on Arch linux. :cry: 

```python
$ ./fildem
/usr/bin/fildem:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Traceback (most recent call last):
  File "/usr/bin/fildem", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3672, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3656, in _call_aside
    f(*args, **kwargs)
    ~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3685, in _initialize_master_working_set
    working_set = _declare_state('object', 'working_set', WorkingSet._build_master())
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    ws.require(__requires__)
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 1070, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 897, in resolve
    dist = self._resolve_dist(
        req, best, replace_conflicting, env, installer, required_by, to_activate
    )
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 938, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fildem==0.6.7' distribution was not found and is required by the application
```
