### ISSUE TITLE
Cannot make it on on TROMjaro

### ISSUE THREAD

**Issue by tiotrom** [gonzaarcr/Fildem#22]
This is another machine I'm testing it on. TROMjaro is a customized Manjaro. So, Arch + Gnome.
I went through all of the install steps and I get this error:
```
[tio@tio-gl753vd Fildem-master]$ ./run.sh
Traceback (most recent call last):
  File "./command.py", line 6, in <module>
    from handlers.default import HudMenu
  File "/home/tio/Downloads/Fildem-master(1)/Fildem-master/handlers/default.py", line 13, in <module>
    from utils.fuzzy import FuzzyMatch
  File "/home/tio/Downloads/Fildem-master(1)/Fildem-master/utils/fuzzy.py", line 3, in <module>
    from fuzzysearch import find_near_matches
ImportError: cannot import name 'find_near_matches' from 'fuzzysearch' (unknown location)

```

Thing is, fuzzysearch is installed:
```
[tio@tio-gl753vd ~]$ sudo pip3 install fuzzysearch
Requirement already satisfied: fuzzysearch in /usr/lib/python3.8/site-packages (0.7.3)
Requirement already satisfied: attrs>=19.3 in /usr/lib/python3.8/site-packages (from fuzzysearch) (20.3.0)
```

Maybe I messed it up since I first installed via AUR from Pacman, then removed it and installed with pip3. How to fix? :D 

Thanks!

**Comment by tiotrom** [comment]
I removed with pip and reinstall with pip fuzzysearch. Now I get this error:
```
[tio@tio-gl753vd Fildem-master]$ ./run.sh
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.gonzaarcr.appmenu': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tio/Downloads/Fildem-master/keybinder.py", line 29, in main
    run_keybinder(default_hud_menu)
  File "/home/tio/Downloads/Fildem-master/keybinder.py", line 20, in run_keybinder
    dbus_menu = DbusMenu()
  File "/home/tio/Downloads/Fildem-master/utils/menu.py", line 268, in __init__
    self._init_window()
  File "/home/tio/Downloads/Fildem-master/utils/menu.py", line 276, in _init_window
    self._update()
  File "/home/tio/Downloads/Fildem-master/utils/menu.py", line 341, in _update
    self._send_msg(top_level_menus)
  File "/home/tio/Downloads/Fildem-master/utils/menu.py", line 346, in _send_msg
    proxy  = self.session.get_object(MyService.BUS_NAME, MyService.BUS_PATH)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.gonzaarcr.appmenu was not provided by any .service files

```
