### ISSUE TITLE
Packaged Installation

### ISSUE THREAD

**Issue by erfanmola** [gonzaarcr/Fildem#29]
Hi, I know this is a time-consuming action, but it would be a very helpful action if some people just maintain packages for Arch, Ubuntu and etc, since manual updating is a real pain !
I have to check this repository every single day to see if any update is available, and after that i have to update extension files  and also the startup script and etc, ,it's like im installing the package for the first time with every single commit

It would be better if someone could maintain packages and do the updating stuffs, I might be able to do it for AUR since im on arch currently, but for ubuntu anyone's volunteery would be appreciated

**Comment by gonzaarcr** [comment]
I could do a .deb, but I need to check if I can install the extension on the user folder or system wide.

**Comment by erfanmola** [comment]
Installing extension locally could suffice, When deb file gets ready, inform on this topic so i start making AUR version of it

**Comment by TROMsite** [comment]
I would love to see this packaged. We would want to integrate into our Linux spin, TROMjaro (tromjaro.com) by default. Thus, it will be tested a lot. I have already tested this for the past months and works great.

**Comment by gonzaarcr** [comment]
I’ve made a python package which is convinient for an easy management, but honestyle doesn’t solve the rest of the problems. I’m looking at doing native packages but there are too many distributions and version. I’m gonna give it a try to a .deb to see if it works.

**Comment by TROMsite** [comment]
If .deb can then be used for AUR too, then I think you got a lot of distros covered. I poked a friend to see if he can be of any help :)

**Comment by erfanmola** [comment]
Using a flatpack, or snap package would fix the pain of packaging for different distros

**Comment by gonzaarcr** [comment]
Pacman can install deb? I didn’t know that...

**Comment by erfanmola** [comment]
Pacman cannot install deb, maintainers intend to extract deb (use it like a zip file) and do the copying files  and etc, based on deb file on their own

**Comment by gonzaarcr** [comment]
I’m gonna change the fuzzysearch dependency to fuzzyweassy, test it and then make a package. I hope it performs well.

**Comment by gonzaarcr** [comment]
I made a quick package. A lot to improve, but I wanted to upload it before going to sleep. It’s the python package wrapped inside a debian, good to know it was useful. After some analysis, I just dropped the fuzzy dependency.

**Comment by TROMsite** [comment]
Awesome @gonzaarcr ! @erfanmola are you going to try and make an AUR out of it?

**Comment by TROMsite** [comment]
We packaged it quickly as AUR and get these errors:
```
could not satisfy dependencies:
- unable to satisfy dependency 'bamfdaemon' required by python3-fildem
- unable to satisfy dependency 'unity-gtk-module-common' required by python3-fildem
```

**Comment by gonzaarcr** [comment]
You will have to change the dependencies since Ubuntu and Arch have different ones.

From the Read Me, this are the Ubuntu dependencies:

```
libbamf3-dev bamfdaemon libkeybinder-3.0-dev appmenu-gtk2-module appmenu-gtk3-module unity-gtk-module-common
```

And this the Arch

```
bamf appmenu-gtk-module libkeybinder3 libdbusmenu-gtk2 libdbusmenu-gtk3 libdbusmenu-qt5
```

The dependencies are in control/control.

**Comment by TROMsite** [comment]
Ok now I get `Error while configuring python3-fildem`

And this is the full output:
```
Preparing...
Resolving dependencies...
Checking inter-conflicts...
Download of libwnck3 (3.36.0-1) started
Download of libxres (1.2.0-2) started
Download of libxres (1.2.0-2) finished
Download of bamf (0.5.5-1) started
Download of bamf (0.5.5-1) finished
Download of libwnck3 (3.36.0-1) finished
Download of appmenu-gtk-module (0.7.6-1) started
Download of appmenu-gtk-module (0.7.6-1) finished
Download of libdbusmenu-gtk2 (16.04.0-4) started
Download of libdbusmenu-gtk2 (16.04.0-4) finished
Checking keyring...
Checking integrity...
Loading packages files...
Checking file conflicts...
Checking available disk space...
Installing libxres (1.2.0-2)...
Installing libwnck3 (3.36.0-1)...
Installing bamf (0.5.5-1)...
Installing appmenu-gtk-module (0.7.6-1)...
Installing libdbusmenu-gtk2 (16.04.0-4)...
Installing python3-fildem (0.6.2-1)...
/tmp/alpm_zKyBzv/.INSTALL: line 23: syntax error near unexpected token `}'
Error while configuring python3-fildem
/tmp/alpm_zKyBzv/.INSTALL: line 23: `}'
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Compiling GSettings XML schema files...
Updating the desktop file MIME type cache...
Transaction successfully finished.
```

**Comment by TROMsite** [comment]
And these are the files that were added to the system:
```
usr/bin/fildem 
/usr/bin/fildem-hud 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/INSTALLER 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/LICENSE.txt 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/METADATA 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/RECORD 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/REQUESTED 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/WHEEL 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/direct_url.json 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/entry_points.txt 
/usr/lib/python3/dist-packages/fildem-0.6.1.dist-info/top_level.txt 
/usr/lib/python3/dist-packages/fildem/init.py 
/usr/lib/python3/dist-packages/fildem/appmenu.py 
/usr/lib/python3/dist-packages/fildem/command.py 
/usr/lib/python3/dist-packages/fildem/handlers/init.py 
/usr/lib/python3/dist-packages/fildem/handlers/default.py 
/usr/lib/python3/dist-packages/fildem/handlers/global_menu.py 
/usr/lib/python3/dist-packages/fildem/handlers/rofi.py 
/usr/lib/python3/dist-packages/fildem/inithud.py 
/usr/lib/python3/dist-packages/fildem/keybinder.py 
/usr/lib/python3/dist-packages/fildem/menu_model/init.py 
/usr/lib/python3/dist-packages/fildem/menu_model/menu_item.py 
/usr/lib/python3/dist-packages/fildem/menu_model/menu_model.py 
/usr/lib/python3/dist-packages/fildem/run.py 
/usr/lib/python3/dist-packages/fildem/utils/init.py 
/usr/lib/python3/dist-packages/fildem/utils/fuzzy.py 
/usr/lib/python3/dist-packages/fildem/utils/global_keybinder.py 
/usr/lib/python3/dist-packages/fildem/utils/menu.py 
/usr/lib/python3/dist-packages/fildem/utils/service.py 
/usr/lib/python3/dist-packages/fildem/utils/window.py 
/usr/share/applications/fildem-hud.desktop
```

**Comment by gonzaarcr** [comment]
```/tmp/alpm_zKyBzv/.INSTALL: line 23: syntax error near unexpected token `}'```

Seems to be a problem of the tools that you are using.

**Comment by TROMsite** [comment]
I am using pacman

**Comment by TROMsite** [comment]
More to that error for Arch/Gnome:
```
Installing python3-fildem (0.6.4-1)...
/tmp/alpm_BuLL94/.INSTALL: line 23: syntax error near unexpected token `}'
Error while configuring python3-fildem
/tmp/alpm_BuLL94/.INSTALL: line 23: `	}'
```
This is the install script:

```post_install() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

	if which py3compile >/dev/null 2>&1; then
		py3compile -p python3-fildem 
	fi
	if which pypy3compile >/dev/null 2>&1; then
		pypy3compile -p python3-fildem  || true
	fi

	update-desktop-database -q
}

post_upgrade() {
	post_install
}

pre_remove() {

	if which py3clean >/dev/null 2>&1; then
		py3clean -p python3-fildem 
	else
	}

post_remove() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	update-desktop-database -q
	}
```

**Comment by TROMsite** [comment]
If I get help with fixing these errors I can test it on Arch Gnome

**Comment by gonzaarcr** [comment]
The `}` on line 11 doesn’t have an opening one, and the `else` on line 21 should be an `fi`

**Comment by TROMsite** [comment]
> on line 21 should be an `fi`

fi or if? I want to make sure is not a typo. And thanks for the tips I'll try to fix these.

**Comment by gonzaarcr** [comment]
If you want to end the command it’s `fi`. If you want to paste verbatim the command from the debian package that function is

```

pre_remove() {
	if which py3clean >/dev/null 2>&1; then
		py3clean -p python3-fildem 
	else
		dpkg -L python3-fildem | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
		find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
	fi
}
```

**Comment by TROMsite** [comment]
Ok thanks now installed successfully. This is the AUR package that I am testing https://www.drive.tromsite.com/s/pSszFGNAiqNg56B - still does not work on tromjaro. Installed fine, insatlled the fildem gnome extension, but does not work. 

On my TROMjaro install on my laptop works perfectly fine using this:
1. Download the repo and install the extension copying/moving the `fildemGMenu@gonza.com` folder into `~/.local/share/gnome-shell/extensions`
2. Install:    ` sudo pacman -S bamf appmenu-gtk-module libkeybinder3 libdbusmenu-gtk2 libdbusmenu-gtk3 libdbusmenu-qt5`
3. Install: `pip3 install fuzzysearch`
4. Go to extensions and enable "fildemGMenu"
5. Reboot your computer
6. Go to the repo folder, and from within, open it in terminal then do: `./run.sh`
7. Test to see if works, if not,
8. Reboot.
9. Do step nr 6 again.  If works:
10. Create a .desktop file in .local/share/applications and name it "global-menu-and-hud". Inside it paste this:

```
[Desktop Entry]
Encoding=UTF-8
Name=GlobalMenu
Comment=TROMjaro Global Menu
Type=Application
Icon=global-menu-and-hud
Exec=bash -c "add here the path where the run.sh file is"
Terminal=false
Categories=Application;Programme;[Desktop Entry]
```

11. Save and Alt + F2 the type "r" to reboot the desktop
12. Search in the menu to see if the file is there
13. Via Tweaks add it to Startup at boot


But in a VM, with TROMjaro. Does not work using the AUR package + the fildem extension. How to debug?

**Comment by TROMsite** [comment]
I see there is a .desktop file that executes: fildem-hud. But when I try to run that in terminal I get:
```fildem-hud                                                       ✔ 
Traceback (most recent call last):
  File "/usr/bin/fildem-hud", line 5, in <module>
    from fildem.inithud import main
ModuleNotFoundError: No module named 'fildem'
```

**Comment by TROMsite** [comment]
And fildem.hud in /usr/bin contains this:
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from fildem.inithud import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by gonzaarcr** [comment]
I was able to do it with the following PKGBUILD

```
pkgname=python3-fildem
pkgver=0.6.4
pkgrel=1
pkgdesc="This project is a fork of gnomehud with the adition of a global menu bar"
arch=('i686' 'x86_64')
url="https://github.com/gonzaarcr/fildem"
depends=('bamf'
         'appmenu-gtk-module'
         'libkeybinder3'
         'libdbusmenu-gtk2'
         'libdbusmenu-gtk3'
         'libdbusmenu-qt5')
makedepends=('git')
provides=("python3-fildem=$pkgver")
source=('git+https://github.com/gonzaarcr/fildem.git')
md5sums=('SKIP')

pkgver() {
    cd "$srcdir/fildem"
    git checkout pypkg &> /dev/null
    git tag | tail -1
}

build() {
    cd "$srcdir/fildem"
    python3 setup.py bdist_wheel
}

check() {
    cd "$srcdir/fildem"
    python3 setup.py test
}

package() {
    cd "$srcdir/fildem"
    python3 setup.py install --skip-build --root=$pkgdir --optimize=1
}
```

**Comment by TROMsite** [comment]
I get this error:
```
==> Starting build()...
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by TROMsite** [comment]
I added the package "python-wheel" for Manjaro. Then I get this error:
```
==> Starting check()...
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
/usr/sbin/python3: No module named pip
error: Command '['/usr/sbin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpo8b8sidu', '--quiet', 'PyGObject>=3.30.0']' returned non-zero exit status 1.
==> ERROR: A failure occurred in check().
    Aborting...
`

**Comment by TROMsite** [comment]
I am trying it here btw https://gitlab.com/tromsite/tromjaro/packages/global-menu

**Comment by gonzaarcr** [comment]
It seems you don’t have pip installed.

**Comment by TROMsite** [comment]
Ok. I added it to the dependency list: python-pip. And I get this now:
```
  running build_ext
  Package gobject-introspection-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'gobject-introspection-1.0', required by 'virtual:world', not found
  Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.56.0')' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for PyGObject
ERROR: Failed to build one or more wheels
error: Command '['/usr/sbin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp2c65au_y', '--quiet', 'PyGObject>=3.30.0']' returned non-zero exit status 1.
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by gonzaarcr** [comment]
I think the check is not needed, just remove it.

**Comment by TROMsite** [comment]
Yup worked after I removed it. Installed it. However does not work at all. Here is the output:
```
                                                 ✔ 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.gonzaarcr.appmenu': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fildem-hud", line 33, in <module>
    sys.exit(load_entry_point('fildem==0.6.4', 'console_scripts', 'fildem-hud')())
  File "/usr/lib/python3.9/site-packages/fildem/inithud.py", line 7, in main
    proxy = session.get_object('com.gonzaarcr.appmenu', '/com/gonzaarcr/appmenu')
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.gonzaarcr.appmenu was not provided by any .service files
```

**Comment by gonzaarcr** [comment]
Start the service before, with `fildem`

**Comment by TROMsite** [comment]
Nice. Works! But can we make the PKGBUILD force fildem service to start? Also, force fildem-hud to start. So that we can make it as easy as installing a package from AUR :D.

**Comment by TROMsite** [comment]
I imagine installing this package and have it work. As simple as that :D. Also, isn't it possible that the same PKGBUILD file to add the extension folder directly from github to the proper gnome-shell/extensions folder? So we have a more complete package?
