### ISSUE TITLE
Some Errors with STM32CubeIDE (aka Eclipse)

### ISSUE THREAD

**Issue by caglarbingol** [gonzaarcr/Fildem#3]
I get this error with STM32CubeIDE (witch use Eclipse to implement) 

Traceback (most recent call last):
  File "/home/caglarbingol/Downloads/Fildem-master/utils/window.py", line 119, in _window_switched_bamf
    cls._call_all_listeners(win)
  File "/home/caglarbingol/Downloads/Fildem-master/utils/window.py", line 129, in _call_all_listeners
    callback(window)
  File "/home/caglarbingol/Downloads/Fildem-master/utils/menu.py", line 273, in on_window_switched
    self._init_window()
  File "/home/caglarbingol/Downloads/Fildem-master/utils/menu.py", line 269, in _init_window
    self._update()
  File "/home/caglarbingol/Downloads/Fildem-master/utils/menu.py", line 309, in _update
    self._update_menus()
  File "/home/caglarbingol/Downloads/Fildem-master/utils/menu.py", line 304, in _update_menus
    self.gtkmenu.get_results()
  File "/home/caglarbingol/Downloads/Fildem-master/utils/menu.py", line 93, in get_results
    interface.End([x for x in range(1024)])
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

**Comment by caglarbingol** [comment]
And this

** (-c:23519): WARNING **: 21:29:54.265: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/54525957

** (-c:23519): WARNING **: 21:29:54.266: Failed to fetch type: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/54525957

** (-c:23519): WARNING **: 21:29:54.267: Failed to fetch monitor: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/54525957

** (-c:23519): WARNING **: 21:29:54.268: Failed to fetch maximized state: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/54525957

** (-c:23519): WARNING **: 21:29:54.268: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/54525957

** (-c:23519): WARNING **: 21:29:54.278: Unable to fetch children: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.view” on object at path /org/ayatana/bamf/application/1136490591


** (-c:23519): WARNING **: 21:29:54.279: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.application” on object at path /org/ayatana/bamf/application/1136490591

**Comment by gonzaarcr** [comment]
I just removed that line, since I’ve never had error without that line. And for the second post, I’m thinking on removing Bamf all together, I don’t like that dependency. It already works without for Wayland, I just add some command line argument to change it

**Comment by Kixero** [comment]
I just got this issue with STM32CubeIDE as well, I had to disable the extension completely.

Is there a fix yet or a way to blacklist apps ?

**Comment by gonzaarcr** [comment]
Should work after e1b786b. I thikn it was some problem with the spash screen, because if the menu was extracted when the program was already running there was no problem.

**Comment by Kixero** [comment]
I tested the fix with STM32CubeIDE. 
It works when the IDE is launched first and run.sh after, but not the other way round.
If the extension is launched at startup for example, the IDE crashes at launch.

I got this error on the IDE side if that can help :

>**
> GLib-GIO:ERROR:../../../gio/gmenuexporter.c:395:g_menu_exporter_group_unsubscribe: assertion failed: (group->subscribed >= count)
Bail out! GLib-GIO:ERROR:../../../gio/gmenuexporter.c:395:g_menu_exporter_group_unsubscribe: assertion failed: (group->subscribed >= count)

**Comment by gonzaarcr** [comment]
At what moment does that error occurs?

**Comment by Kixero** [comment]
First there is a splash screen, then the workspace folder prompt, then the splash screen again for a few seconds and then it crashes and outputs this error.
It seems that the error occurs when it tries to display the IDE main window.

**Comment by gonzaarcr** [comment]
I’ll keep trying to replicate the bug. Probably it would work using try everywhere, but I don’t want to break other stuff.
