### ISSUE TITLE
Global menu without support for JAVA applications

### ISSUE THREAD

**Issue by williamcanin** [gonzaarcr/Fildem#42]
Hi, it looks like it doesn't have support for JAVA applications, like the ides of jetbrains (PyCharm, Intelij etc). I know that it must be a very complex obstacle to solve this, because when I use another global menu in XFCE, it had this lack of support for these applications.

**Comment by gonzaarcr** [comment]
For the Jetbrains IDE’s try to install the plugin [JavaFX runtime](https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins). it could behave better, i’m working on it.

**Comment by amirhossein-ka** [comment]
> For the Jetbrains IDE’s try to install the plugin [JavaFX runtime](https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins). it could behave better, i’m working on it.

hi
i've installed that plugin on goland and it's showing the buttons but when i click on them nothing happen and i get this error

```
Traceback (most recent call last):
  File "/home/amir/.local/share/fildem/handlers/global_menu.py", line 323, in do_activate
    self.add_menus()
  File "/home/amir/.local/share/fildem/handlers/global_menu.py", line 332, in add_menus
    self.window.set_menu(self.dbus_menu.items)
  File "/home/amir/.local/share/fildem/handlers/global_menu.py", line 189, in set_menu
    if item.path[0] == current_prefix:
IndexError: list index out of range
```

**Comment by dyanfelipe** [comment]
the buttons on the top bar don't work for me!

**Comment by nkcong206** [comment]
I also encountered a similar situation.  pycharm works but intellij doesn't.

**Comment by dyanfelipe** [comment]
Do you find a solution?

**Comment by 7system7** [comment]
Ehh, I realized that, I had the same error. :( #108

**Comment by wthsths** [comment]
This issue has disappeared in GoLand 2022.1. Can someone confirm in other IDEs of Jetbrains too?

**Comment by 7system7** [comment]
In PHPStorm 2022.1 it still occurs.

**Comment by fabian-st** [comment]
Still occurs in RubyMine and IntelliJ Idea CE 2022.2 with JavaFX Runtime installed. A fix would be much appreciated.
