### ISSUE TITLE
Erro in ./run.sh

### ISSUE THREAD

**Issue by guilhermeoliveiralopes** [gonzaarcr/Fildem#49]
Erro:
/run.sh: linha 6: [: =: esperava operador unário
Traceback (most recent call last):
  File "./command.py", line 6, in <module>
    from handlers.default import HudMenu
  File "/home/guilhermelopes/.local/share/fildem/handlers/default.py", line 16, in <module>
    from utils.window import WindowActions, backend
  File "/home/guilhermelopes/.local/share/fildem/utils/window.py", line 16, in <module>
    backend = os.environ['XDG_SESSION_TYPE']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_SESSION_TYPE'

**Comment by gonzaarcr** [comment]
Should work after 8c04c1b

**Comment by guilhermeoliveiralopes** [comment]
Ok thanks!
