### ISSUE TITLE
show error after run fildem in terminal ubuntu 21.04 wayland gnome 3.38

### ISSUE THREAD

**Issue by anishkumar127** [gonzaarcr/Fildem#73]
(-c:23876): Gtk-CRITICAL **: 16:56:29.246: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.253: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.253: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.258: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.259: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.260: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.265: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.265: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.267: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:29.276: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-WARNING **: 16:56:29.294: no trigger event for menu popup

(-c:23876): Gtk-CRITICAL **: 16:56:56.082: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.091: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.091: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.099: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.099: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.100: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.106: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.106: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.108: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-CRITICAL **: 16:56:56.117: gtk_accel_group_connect: assertion 'accel_key > 0' failed

(-c:23876): Gtk-WARNING **: 16:56:56.123: no trigger event for menu popup

**Comment by anishkumar127** [comment]
(-c:28254): Gtk-WARNING **: 18:18:55.093: no trigger event for menu popup
ERROR:dbus.proxies:Introspect error on :1.1071:/org/gnome/gedit: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.1071 was not provided by any .service files
ERROR:dbus.connection:Unable to set arguments ('preferences', [], {}) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fildem/handlers/global_menu.py", line 358, in <lambda>
    callback = lambda a, b: self.dbus_menu.activate(path)
  File "/usr/lib/python3/dist-packages/fildem/utils/menu.py", line 169, in activate
    self.gtkmenu.activate(selection)
  File "/usr/lib/python3/dist-packages/fildem/menu_model/menu_model.py", line 31, in activate
    self.send_action(action, 'app.', self.app_path)
  File "/usr/lib/python3/dist-packages/fildem/menu_model/menu_model.py", line 41, in send_action
    interface.Activate(name.replace(prefix, ''), [], dict())
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty list
ERROR:dbus.proxies:Introspect error on :1.1071:/org/gnome/gedit/window/1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.1071 was not provided by any .service files
ERROR:dbus.connection:Unable to set arguments ('replace', [], {}) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fildem/handlers/global_menu.py", line 358, in <lambda>
    callback = lambda a, b: self.dbus_menu.activate(path)
  File "/usr/lib/python3/dist-packages/fildem/utils/menu.py", line 169, in activate
    self.gtkmenu.activate(selection)
  File "/usr/lib/python3/dist-packages/fildem/menu_model/menu_model.py", line 33, in activate
    self.send_action(action, 'win.', self.win_path)
  File "/usr/lib/python3/dist-packages/fildem/menu_model/menu_model.py", line 41, in send_action
    interface.Activate(name.replace(prefix, ''), [], dict())
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty list
