### ISSUE TITLE
fildem-hud error

### ISSUE THREAD

**Issue by jakubiszon26** [gonzaarcr/Fildem#84]
### Information

- **Operating System**:  
```jakub@pop-os:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy
```
- **Gnome Shell Version**: 
```GNOME 3.38.3```
- **Xorg/Wayland?**: 
```Xorg```
- **Apps tested**:  
```gnome terminal, edge beta```
- **Fildem version**: 
```latest```

### What is the current behavior?
Menu is not showing at all
fildem-hud returns following error: 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.gonzaarcr.appmenu': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fildem-hud", line 11, in <module>
    load_entry_point('fildem==0.6.7', 'console_scripts', 'fildem-hud')()
  File "/usr/lib/python3/dist-packages/fildem/inithud.py", line 7, in main
    proxy = session.get_object('com.gonzaarcr.appmenu', '/com/gonzaarcr/appmenu')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.gonzaarcr.appmenu was not provided by any .service files
```

**Comment by FCollaPi** [comment]
I'm having the same issue on Ubuntu 20.04

**Comment by AJJLagerweij** [comment]
Same here on ubuntu 20.04. I turned off all my themes and other extensions, but still see this error.

**Comment by ArseniySavin** [comment]
Hi
Try to do this.
Open repository.
- Try copy folder ** fildem ** to ** ~ / .local / lib / python3.9 / site-packages **
- Copy ** fildem-hud.desktop ** file to ** ~ / .local / share / applications **
- Create second copy ** fildem-hud.desktop ** and rename ** fildem.desktop **
- Edit ** fildem.desktop **. Change all string when found _fildem-hud_ and replace for _fildem_, save file
- Open __Gnome Tweak Tool__ go to _Startup Applications_ and first adding _fildem_ then second _fildem-hud_
Login out and log in. The menu will work.

**Comment by AJJLagerweij** [comment]
I can confirm that this works.

**Comment by Surmiloo** [comment]
> 

sorry i can't find fildem.desktop or fildem-hud.desktop in my archlinux

**Comment by Surmiloo** [comment]
> Hi Try to do this. Open repository.
> 
> * Try copy folder **fildem** to **~/.local/lib/python3.9/site-packages**
> * Copy **fildem-hud.desktop** file to **~/.local/share/applications**
> * Create second copy **fildem-hud.desktop** and rename **fildem.desktop**
> * Edit **fildem.desktop**. Change all string when found _fildem-hud_ and replace for _fildem_, save file
> * Open **Gnome Tweak Tool** go to _Startup Applications_ and first adding _fildem_ then second _fildem-hud_
>   Login out and log in. The menu will work.

i can't find fildem-hud.desktop or fildem.desktop in archlinux

**Comment by Mingrui-Huang** [comment]
thank you ArseniySavin.it's work!
